build_mode = "release"
target_adapters = []
target_platforms = ["android"]
ios = [
    "aarch64-apple-ios-sim",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
]
android = [
    "x86_64-linux-android",
    "aarch64-linux-android",
]
